In [1]:
import pandas as pd
import sys
sys.path.append('./')

In [20]:
df = pd.read_csv('/Users/iqraimtiaz/Documents/duke/Courses/Ids-721/Job-Recommendation-System/data/dataworld-jobs.csv')
df.columns

Index(['Unnamed: 0', 'Job Title', 'Job Description', 'Job Type', 'Categories',
       'Location', 'City', 'State', 'Country', 'Zip Code', 'Address',
       'Salary From', 'Salary To', 'Salary Period', 'Apply Url', 'Apply Email',
       'Employees', 'Industry', 'Company Name', 'Employer Email',
       'Employer Website', 'Employer Phone', 'Employer Logo',
       'Companydescription', 'Employer Location', 'Employer City',
       'Employer State', 'Employer Country', 'Employer Zip Code', 'Uniq Id',
       'Crawl Timestamp'],
      dtype='object')

In [19]:
df = df.dropna()
df

Empty DataFrame
Columns: [Unnamed: 0, Job Title, Job Description, Job Type, Categories, Location, City, State, Country, Zip Code, Address, Salary From, Salary To, Salary Period, Apply Url, Apply Email, Employees, Industry, Company Name, Employer Email, Employer Website, Employer Phone, Employer Logo, Companydescription, Employer Location, Employer City, Employer State, Employer Country, Employer Zip Code, Uniq Id, Crawl Timestamp]
Index: []

[0 rows x 31 columns]

In [10]:
from bs4 import BeautifulSoup

from bs4 import BeautifulSoup
import pandas as pd
import multiprocessing

# define a function to apply the get_text() method to each element
def html_to_string(html):
    return BeautifulSoup(html, 'html.parser').get_text()

# apply the function to each element of the column using multiprocessing
with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
    df['Job Description'] = pool.map(html_to_string, df['Job Description'])

# print the updated DataFrame
print(df)

                                              Job Title  \
0                                         Shift Manager
1                            Operations Support Manager
2                         Senior Product Manager - Data
3                            Part-Time Office Concierge
4                           Print & Marketing Associate
...                                                 ...
29997                                  Bilingual Teller
29998                  Rental Consultant - Harrison, OH
29999                      Product Support Specialist 5
30000                   Marketing Strategist (Contract)
30001  Business Intelligence Data Warehouse ETL Manager

                                         Job Description  Job Type  \
0      WE ARE LOOKING FOR TOP PERFORMERS TO GROW WITH...       NaN
1      \n\nJOB PURPOSE: This position is responsible ...       NaN
2      Product Manager - Unique opportunity with a mo...       NaN
3      \nColdwell Banker in Festus, Missouri is looki...       NaN
4      \nDescription\nPosition Summary:\n\nThe Copy a...       NaN
...                                                  ...       ...
29997  A little about us!\n\nMoneytree is a family-ru...       NaN
29998  \nSelf-Storage Rental Consultant - Full Time -...       NaN
29999  The Product Support Specialist is responsible ...       NaN
30000  \nTogether, Let’s Make A Difference.\n\n\n\nAt...       NaN
30001  \nThis is a full-time, permanent Business Inte...       NaN

       Categories                 Location           City State  \
0             NaN  Mission Hills, CA 91345  Mission Hills    CA
1             NaN        Atlanta, GA 30342        Atlanta    GA
2             NaN              Chicago, IL        Chicago    IL
3             NaN               Festus, MO         Festus    MO
4             NaN   Cedar Rapids, IA 52404   Cedar Rapids    IA
...           ...                      ...            ...   ...
29997         NaN       Lakewood, CO 80226       Lakewood    CO
29998         NaN       Harrison, OH 45030       Harrison    OH
29999         NaN      Melbourne, FL 32940      Melbourne    FL
30000         NaN            San Diego, CA      San Diego    CA
30001         NaN            Jefferson, WI      Jefferson    WI

             Country Zip Code  Address  ...  Employer Phone  \
0      United States    91345      NaN  ...             NaN
1      United States    30342      NaN  ...             NaN
2      United States      NaN      NaN  ...             NaN
3      United States      NaN      NaN  ...             NaN
4      United States    52404      NaN  ...             NaN
...              ...      ...      ...  ...             ...
29997  United States    80226      NaN  ...             NaN
29998  United States    45030      NaN  ...             NaN
29999  United States    32940      NaN  ...             NaN
30000  United States      NaN      NaN  ...             NaN
30001  United States      NaN      NaN  ...             NaN

                                           Employer Logo  \
0      https://d2q79iu7y748jz.cloudfront.net/s/_squar...
1      https://d2q79iu7y748jz.cloudfront.net/s/_logo/...
2                                                    NaN
3                                                    NaN
4      https://d2q79iu7y748jz.cloudfront.net/s/_logo/...
...                                                  ...
29997  https://d2q79iu7y748jz.cloudfront.net/s/_logo/...
29998                                                NaN
29999                                                NaN
30000  https://d2q79iu7y748jz.cloudfront.net/s/_logo/...
30001                                                NaN

                                      Companydescription  \
0      Del Taco is an American quick service restaura...
1      Based in Atlanta, FOCUS Brands Inc. is an inno...
2      Vibes Corp. reputation was built and establish...
3                                                    NaN
4      Staples is The Worklife Fulfillment Company, h...
...                                                  ...
29997  Moneytree is a family-run business that has be...
29998                                                NaN
29999                                                NaN
30000  Ajinomoto Bio-Pharma Services is a fully integ...
30001  NewCareers is a full service executive/profess...

             Employer Location  Employer City  Employer State  \
0      Mission Hills, CA 91345  Mission Hills              CA
1                          NaN            NaN             NaN
2                          NaN            NaN             NaN
3                          NaN            NaN             NaN
4       Cedar Rapids, IA 52404   Cedar Rapids              IA
...                        ...            ...             ...
29997                      NaN            NaN             NaN
29998                      NaN            NaN             NaN
29999                      NaN            NaN             NaN
30000                      NaN            NaN             NaN
30001                      NaN            NaN             NaN

       Employer Country Employer Zip Code                           Uniq Id  \
0         United States             91345  511f9a53920f4641d701d51d3589349f
1         United States               NaN  4955daf0a3facbe2acb6c429ba394e6d
2         United States               NaN  a0e0d12df1571962b785f17f43ceae12
3         United States               NaN  56e411fd731f76ac916bf4fb169250e9
4         United States             52404  3fff5c0ad6981bf4bff6260bd5feab63
...                 ...               ...                               ...
29997     United States               NaN  db18d0e2de28df6e1e605a3800ffd574
29998     United States               NaN  47f8d7f320223b6f043ef5c345676902
29999     United States               NaN  d2a18fb9f52495aa7876d4470e5acc61
30000     United States               NaN  ce699d2e94a52dfebb13bcf70ed5ffd7
30001     United States               NaN  4c13eed829c37b7d6ec0c94f6374a112

                 Crawl Timestamp
0      2019-08-24 09:13:18 +0000
1      2019-09-19 08:16:55 +0000
2      2019-09-18 02:13:10 +0000
3      2019-10-24 16:39:13 +0000
4      2019-08-24 22:29:10 +0000
...                          ...
29997  2019-10-25 22:42:37 +0000
29998  2019-10-25 16:56:18 +0000
29999  2019-10-25 01:39:48 +0000
30000  2019-08-23 15:36:47 +0000
30001  2019-10-24 14:44:39 +0000

[30002 rows x 30 columns]

In [15]:
df.to_csv('/Users/iqraimtiaz/Documents/duke/Courses/Ids-721/Job-Recommendation-System/data/dataworld-jobs.csv')

In [8]:
#df = df[df['jobpost','date','Title','Company','Eligibility','Location','JobDescription','JobRequirment','RequiredQual','ApplicationP']]
#df        

# show only specific columns
df[['jobpost','date','Title','Company','Eligibility','Location','JobDescription','JobRequirment','RequiredQual','ApplicationP']]

,jobpost,date,Title,Company,Eligibility,Location,JobDescription,JobRequirment,RequiredQual,ApplicationP
0,AMERIA Investment Consulting Company\r\nJOB TI...,"Jan 5, 2004",Chief Financial Officer,AMERIA Investment Consulting Company,NaN,"Yerevan, Armenia",AMERIA Investment Consulting Company is seekin...,- Supervises financial management and administ...,"To perform this job successfully, an\r\nindivi...","To apply for this position, please submit a\r\..."
1,International Research & Exchanges Board (IREX...,"Jan 7, 2004",Full-time Community Connections Intern (paid i...,International Research & Exchanges Board (IREX),NaN,"IREX Armenia Main Office; Yerevan, Armenia \r\...",NaN,NaN,- Bachelor's Degree; Master's is preferred;\r\...,Please submit a cover letter and resume to:\r\...
2,Caucasus Environmental NGO Network (CENN)\r\nJ...,"Jan 7, 2004",Country Coordinator,Caucasus Environmental NGO Network (CENN),NaN,"Yerevan, Armenia",Public outreach and strengthening of a growing...,- Working with the Country Director to provide...,"- Degree in environmentally related field, or ...",Please send resume or CV toursula.kazarian@......
3,Manoff Group\r\nJOB TITLE: BCC Specialist\r\n...,"Jan 7, 2004",BCC Specialist,Manoff Group,NaN,"Manila, Philippines",The LEAD (Local Enhancement and Development fo...,- Identify gaps in knowledge and overseeing in...,"- Advanced degree in public health, social sci...",Please send cover letter and resume to Amy\r\n...
4,Yerevan Brandy Company\r\nJOB TITLE: Software...,"Jan 10, 2004",Software Developer,Yerevan Brandy Company,NaN,"Yerevan, Armenia",NaN,- Rendering technical assistance to Database M...,- University degree; economical background is ...,Successful candidates should submit\r\n- CV; \...
...,...,...,...,...,...,...,...,...,...,...
18996,Technolinguistics NGO\r\n\r\n\r\nTITLE: Senio...,"Dec 28, 2015",Senior Creative UX/ UI Designer,Technolinguistics NGO,NaN,"Yerevan, Armenia",A tech startup of Technolinguistics based in N...,- Work closely with product and business teams...,- At least 5 years of experience in Interface/...,"To apply for this position, please send your\r..."
18997,"""Coca-Cola Hellenic Bottling Company Armenia"" ...","Dec 30, 2015",Category Development Manager,"""Coca-Cola Hellenic Bottling Company Armenia"" ...",All interested professionals.,"Yerevan, Armenia",NaN,- Establish and manage Category Management dev...,"- University degree, ideally business related;...",All interested candidates are kindly requested...
18998,"""Coca-Cola Hellenic Bottling Company Armenia"" ...","Dec 30, 2015",Operational Marketing Manager,"""Coca-Cola Hellenic Bottling Company Armenia"" ...",All interested professionals.,"Yerevan, Armenia",NaN,"- Develop, establish and maintain marketing st...","- Degree in Business, Marketing or a related f...",All interested candidates are kindly requested...
18999,San Lazzaro LLC\r\n\r\n\r\nTITLE: Head of O...,"Dec 30, 2015",Head of Online Sales Department,San Lazzaro LLC,NaN,"Yerevan, Armenia",San Lazzaro LLC is looking for a well-experien...,- Handle the project activites of the online s...,- At least 1 year of experience in online sale...,Interested candidates can send their CVs to:\r...
19000,"""Kamurj"" UCO CJSC\r\n\r\n\r\nTITLE: Lawyer in...","Dec 30, 2015",Lawyer in Legal Department,"""Kamurj"" UCO CJSC",NaN,"Yerevan, Armenia","""Kamurj"" UCO CJSC is looking for a Lawyer in L...",- Properly provide internal legal services of ...,- Higher legal education; Master's degree is a...,All qualified applicants are encouraged to\r\n...